name: Metrics
on:
  schedule: [{cron: "0 6,12,18 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          config_display: columns
          user: MarkTuddenham
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_code: yes
          plugin_code_days: 7
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_skipped: marktuddenham
          plugin_code_visibility: public
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_ignored: html, css, Jupyter Notebook
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_details: percentage, lines
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_lines: yes
          plugin_pagespeed: no
          plugin_pagespeed_url: .user.website
          plugin_stars: yes
          plugin_stars_limit: 4
